-- StoryEngine durable content plane for Supabase.
-- Server-only by default: no anon/authenticated policies or grants.
-- The Railway/API server must authenticate with a server secret before cutover.
-- Existing compatible tables are adopted; incompatible pre-existing shapes fail closed
-- through the contract checks at the end of this migration.

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  workspace_id text not null unique,
  title text not null,
  genre text,
  pitch text,
  mode text,
  tenant_id text not null,
  created_by_actor_id text not null,
  schema_version text not null default '1.0.0',
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.workspace_memberships (
  workspace_id text not null,
  tenant_id text not null,
  actor_id text not null,
  role text not null default 'creator',
  created_at bigint not null,
  primary key (workspace_id, tenant_id, actor_id),
  constraint workspace_memberships_role_check
    check (role in ('viewer', 'creator', 'editor', 'reviewer', 'release_manager', 'administrator'))
);

create table if not exists public.outlines (
  id bigint generated by default as identity primary key,
  workspace_id text not null unique references public.stories(workspace_id) on delete cascade,
  content text,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.stories(workspace_id) on delete cascade,
  chapter_id text,
  title text not null,
  content text,
  text text not null default '',
  status text not null default 'Drafted',
  position integer not null default 0,
  created_at bigint not null,
  updated_at bigint not null,
  unique (workspace_id, chapter_id)
);

create table if not exists public.story_artifacts (
  id bigint generated by default as identity primary key,
  artifact_id text not null unique,
  run_id text not null,
  workspace_id text not null references public.stories(workspace_id) on delete cascade,
  kind text not null,
  title text not null,
  status text not null,
  content_hash text not null,
  html text not null,
  metadata_json text not null default '{}',
  validation_json text not null default '{}',
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists idx_stories_tenant
  on public.stories (tenant_id, updated_at desc);
create index if not exists idx_workspace_memberships_actor
  on public.workspace_memberships (tenant_id, actor_id, workspace_id);
create index if not exists idx_chapters_workspace_position
  on public.chapters (workspace_id, position, id);
create index if not exists idx_story_artifacts_workspace
  on public.story_artifacts (workspace_id, created_at desc);

alter table public.stories enable row level security;
alter table public.stories force row level security;
alter table public.workspace_memberships enable row level security;
alter table public.workspace_memberships force row level security;
alter table public.outlines enable row level security;
alter table public.outlines force row level security;
alter table public.chapters enable row level security;
alter table public.chapters force row level security;
alter table public.story_artifacts enable row level security;
alter table public.story_artifacts force row level security;

-- No browser/client role is granted direct access while StoryEngine still uses its
-- own server session/tenant authority. A later Supabase Auth migration must add
-- explicit tenant-aware policies before granting authenticated access.
revoke all on table public.stories from anon, authenticated;
revoke all on table public.workspace_memberships from anon, authenticated;
revoke all on table public.outlines from anon, authenticated;
revoke all on table public.chapters from anon, authenticated;
revoke all on table public.story_artifacts from anon, authenticated;

grant all on table public.stories to service_role;
grant all on table public.workspace_memberships to service_role;
grant all on table public.outlines to service_role;
grant all on table public.chapters to service_role;
grant all on table public.story_artifacts to service_role;

grant usage, select on sequence public.stories_id_seq to service_role;
grant usage, select on sequence public.outlines_id_seq to service_role;
grant usage, select on sequence public.chapters_id_seq to service_role;
grant usage, select on sequence public.story_artifacts_id_seq to service_role;

comment on table public.stories is 'StoryEngine durable creator story state. Server-authorized only until Supabase Auth cutover.';
comment on table public.workspace_memberships is 'StoryEngine durable tenant/workspace membership state.';
comment on table public.outlines is 'StoryEngine durable outline state.';
comment on table public.chapters is 'StoryEngine durable chapter/manuscript state.';
comment on table public.story_artifacts is 'StoryEngine durable generated artifact state.';

-- Fail closed if an existing manually-created table with one of these names does
-- not satisfy the minimum contract expected by StoryEngine. This prevents an
-- idempotent CREATE TABLE IF NOT EXISTS from producing a false-green migration.
do $$
declare
  missing text;
begin
  select string_agg(required.column_name, ', ' order by required.column_name)
    into missing
  from (
    values
      ('stories', 'workspace_id'),
      ('stories', 'tenant_id'),
      ('stories', 'created_by_actor_id'),
      ('workspace_memberships', 'workspace_id'),
      ('workspace_memberships', 'tenant_id'),
      ('workspace_memberships', 'actor_id'),
      ('outlines', 'workspace_id'),
      ('chapters', 'workspace_id'),
      ('chapters', 'chapter_id'),
      ('story_artifacts', 'artifact_id'),
      ('story_artifacts', 'workspace_id'),
      ('story_artifacts', 'validation_json')
  ) as required(table_name, column_name)
  left join information_schema.columns c
    on c.table_schema = 'public'
   and c.table_name = required.table_name
   and c.column_name = required.column_name
  where c.column_name is null;

  if missing is not null then
    raise exception 'StoryEngine Supabase content-plane contract missing required columns: %', missing;
  end if;
end $$;